/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* The SASL app name for the qpid Broker */
#define BROKER_SASL_NAME "qpidd"

/* Define to 1 if you have the <boost/shared_ptr.hpp> header file. */
#define HAVE_BOOST_SHARED_PTR_HPP 1

/* Define to 1 if you have the `clock_gettime' function. */
#define HAVE_CLOCK_GETTIME 1

/* Define to 1 if you have the `clock_settime' function. */
#define HAVE_CLOCK_SETTIME 1

/* Define to 1 if you have the <corosync/cpg.h> header file. */
/* #undef HAVE_COROSYNC_CPG_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <infiniband/verbs.h> header file. */
#define HAVE_INFINIBAND_VERBS_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <libcman.h> header file. */
#define HAVE_LIBCMAN_H 1

/* Define to 1 if you have the `ibverbs' library (-libverbs). */
#define HAVE_LIBIBVERBS 1

/* Define to 1 if you have the `rdmacm' library (-lrdmacm). */
#define HAVE_LIBRDMACM 1

/* Define to 1 if you have the `sasl2' library (-lsasl2). */
#define HAVE_LIBSASL2 1

/* Define to 1 if you have the `xerces-c' library (-lxerces-c). */
#define HAVE_LIBXERCES_C 1

/* Define to 1 if you have the `xqilla' library (-lxqilla). */
#define HAVE_LIBXQILLA 1

/* Set to 1 whether LOG_AUTHPRIV is supported. */
#define HAVE_LOG_AUTHPRIV 1

/* Set to 1 whether LOG_FTP is supported. */
#define HAVE_LOG_FTP 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <openais/cpg.h> header file. */
#define HAVE_OPENAIS_CPG_H 1

/* Define to 1 if you have the <port.h> header file. */
/* #undef HAVE_PORT_H */

/* Define to 1 if you have the <rdma/rdma_cma.h> header file. */
#define HAVE_RDMA_RDMA_CMA_H 1

/* Enable if libsasl is present */
#define HAVE_SASL 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/epoll.h> header file. */
#define HAVE_SYS_EPOLL_H 1

/* Define to 1 if you have the <sys/poll.h> header file. */
#define HAVE_SYS_POLL_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <uuid/uuid.h> header file. */
#define HAVE_UUID_UUID_H 1

/* Compile-in XML Exchange support. */
#define HAVE_XML 1

/* Define to 1 if your C compiler doesn't accept -c and -o together. */
/* #undef NO_MINUS_C_MINUS_O */

/* Name of package */
#define PACKAGE "qpidc"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "dev@qpid.apache.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "qpidc"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "qpidc 0.5"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "qpidc"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.5"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.5"

/* Define to 1 if on AIX 3.
   System headers sometimes define this.
   We just want to avoid a redefinition error message.  */
#ifndef _ALL_SOURCE
/* # undef _ALL_SOURCE */
#endif

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif

/* Define to 1 if on MINIX. */
/* #undef _MINIX */

/* Define to 2 if the system does not provide POSIX.1 features except with
   this defined. */
/* #undef _POSIX_1_SOURCE */

/* Define to 1 if you need to in order for `stat' and other things to work. */
/* #undef _POSIX_SOURCE */

/* Enable extensions on Solaris.  */
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif

/* Define to 1 if the compiler is checking for lint. */
#define lint 1
